export const MOVEMENT_STATUS = {
    PAID: 'PAID',
    UNPAID: 'UNPAID'
};

export const MOVEMENT_TYPES = {
    INCOME: 'INCOME',
    EXPENSE: 'EXPENSE'
};

export const ACTIONS = {
    ADD_MOVEMENT: 'ADD_MOVEMENT',
    REMOVE_MOVEMENT: 'REMOVE_MOVEMENT',
    EDIT_CONCEPT: 'EDIT_CONCEPT',
    EDIT_VALUE: 'EDIT_VALUE',
    TOGGLE_TYPE: 'TOGGLE_TYPE',
    TOGGLE_STATUS: 'TOGGLE_STATUS',
    ADD_PERIOD: 'ADD_PERIOD',
    REMOVE_PERIOD: 'REMOVE_PERIOD',
    EDIT_NOTE: 'EDIT_NOTE',
    EDIT_NAME: 'EDIT_NAME',
    EDIT_START_DATE: 'EDIT_START_DATE',
    EDIT_END_DATE: 'EDIT_END_DATE',
    TOGGLE_INFO: 'TOGGLE_INFO',
    SWITCH_PERIOD: 'SWITCH_PERIOD',
};